import React, { useEffect, useState } from 'react';
import { UserPreferences, AppScreen } from '../types';
import { FileText, BookOpen, Quote, Star, Send } from 'lucide-react';

interface DashboardProps {
  user: UserPreferences;
  onNavigate: (screen: AppScreen) => void;
}

const Dashboard: React.FC<DashboardProps> = ({ user, onNavigate }) => {
  const [greeting, setGreeting] = useState('');

  useEffect(() => {
    const hours = new Date().getHours();
    if (hours < 12) setGreeting('Good Morning');
    else if (hours < 18) setGreeting('Good Afternoon');
    else setGreeting('Good Evening');
  }, []);

  const fakeReviews = [
    { name: "Sarah K.", text: "This app literally saved my chemistry grades!", rating: 5 },
    { name: "Rahul M.", text: "The AI explanation is better than my professor.", rating: 5 },
    { name: "Anita D.", text: "Flashcards are so addictive. Love it.", rating: 5 },
    { name: "John Doe", text: "Finally a distraction free study app.", rating: 4 },
  ];

  return (
    <div className="bg-slate-50 min-h-full pb-32">
      {/* 1. Header: Name & Greeting */}
      <header className="px-6 pt-8 pb-4 flex justify-between items-center bg-white sticky top-0 z-20 border-b border-slate-50">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">{greeting}, {user.name.split(' ')[0]}</h1>
          <p className="text-slate-500 text-xs font-bold uppercase tracking-wider mt-1">Let's be productive</p>
        </div>
        {/* Profile button removed as requested */}
      </header>

      {/* 2. Scrollable Banner (Right to Left) */}
      <div className="mt-4 overflow-x-auto no-scrollbar snap-x snap-mandatory flex gap-4 px-6 pb-4">
        <div className="snap-center shrink-0 w-[85%] bg-gradient-to-r from-blue-600 to-blue-500 rounded-2xl p-5 text-white shadow-lg shadow-blue-200 relative overflow-hidden">
           <div className="absolute right-0 top-0 w-32 h-32 bg-white opacity-10 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <h3 className="font-bold text-xl mb-1">Ace Your Exams</h3>
           <p className="text-blue-100 text-sm mb-4 max-w-[80%]">Get personalized study plans generated by Isus AI.</p>
           <button onClick={() => onNavigate(AppScreen.STUDY_PLANNER)} className="bg-white text-blue-600 px-4 py-2 rounded-lg text-xs font-bold shadow-sm">Try Now</button>
        </div>
        <div className="snap-center shrink-0 w-[85%] bg-gradient-to-r from-purple-600 to-purple-500 rounded-2xl p-5 text-white shadow-lg shadow-purple-200 relative overflow-hidden">
           <div className="absolute right-0 top-0 w-32 h-32 bg-white opacity-10 rounded-full blur-2xl -mr-10 -mt-10"></div>
           <h3 className="font-bold text-xl mb-1">Master Concepts</h3>
           <p className="text-purple-100 text-sm mb-4 max-w-[80%]">Use flashcards to retain information longer.</p>
           <button onClick={() => onNavigate(AppScreen.FLASHCARDS)} className="bg-white text-purple-600 px-4 py-2 rounded-lg text-xs font-bold shadow-sm">Start Review</button>
        </div>
      </div>

      {/* 3. Two Main Buttons: Notes & Practice */}
      <div className="px-6 grid grid-cols-2 gap-4 mt-2">
        <button 
          onClick={() => onNavigate(AppScreen.NOTES)}
          className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 flex flex-col items-center justify-center gap-3 active:scale-95 transition-transform group hover:border-orange-200"
        >
           <div className="w-14 h-14 bg-orange-50 text-orange-500 rounded-2xl flex items-center justify-center shadow-inner group-hover:scale-110 transition-transform">
             <FileText size={28} />
           </div>
           <span className="font-bold text-slate-800 text-sm">Notes</span>
        </button>
        
        <button 
          onClick={() => onNavigate(AppScreen.STUDY_HUB)}
          className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 flex flex-col items-center justify-center gap-3 active:scale-95 transition-transform group hover:border-emerald-200"
        >
           <div className="w-14 h-14 bg-emerald-50 text-emerald-500 rounded-2xl flex items-center justify-center shadow-inner group-hover:scale-110 transition-transform">
             <BookOpen size={28} />
           </div>
           <span className="font-bold text-slate-800 text-sm">Practice</span>
        </button>
      </div>

      {/* 4. Quote Section */}
      <div className="px-6 mt-8">
        <div className="bg-slate-900 rounded-3xl p-6 text-center relative overflow-hidden">
          <Quote className="absolute top-4 left-4 text-slate-700 opacity-50" size={40} />
          <p className="text-slate-200 text-sm font-medium italic leading-relaxed relative z-10">
            "Success is the sum of small efforts, repeated day in and day out."
          </p>
          <p className="text-slate-500 text-[10px] font-bold uppercase tracking-widest mt-3">— Robert Collier</p>
        </div>
      </div>

      {/* 5. Fake Reviews (Horizontal Scroll) */}
      <div className="mt-8">
        <h3 className="px-6 text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Community Love</h3>
        <div className="overflow-x-auto no-scrollbar flex gap-4 px-6 pb-2">
           {fakeReviews.map((review, i) => (
             <div key={i} className="shrink-0 w-60 bg-white p-4 rounded-2xl shadow-sm border border-slate-100">
                <div className="flex gap-1 mb-2">
                  {[...Array(review.rating)].map((_, j) => <Star key={j} size={12} className="fill-amber-400 text-amber-400" />)}
                </div>
                <p className="text-slate-600 text-xs italic mb-2 line-clamp-2">"{review.text}"</p>
                <p className="text-slate-900 text-[10px] font-bold">{review.name}</p>
             </div>
           ))}
        </div>
      </div>

      {/* 6. Telegram Group Button */}
      <div className="px-6 mt-10 mb-6">
        <button 
          onClick={() => window.open('https://telegram.org', '_blank')}
          className="w-full bg-[#0088cc] hover:bg-[#0077b5] text-white py-4 rounded-2xl shadow-xl shadow-blue-200 flex items-center justify-center gap-3 font-bold transition-all active:scale-95"
        >
           <Send size={20} />
           <span>Join Telegram Group</span>
        </button>
        <p className="text-center text-[10px] text-slate-400 mt-2 font-medium">Get exclusive study materials & updates</p>
      </div>

    </div>
  );
};

export default Dashboard;